name: Klefaski 1 day before
on:
  schedule:
    - cron: '0 9 * * 4'  # Every Thursday at 9:00 UTC - 24 hours before TC time
  workflow_dispatch: 

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.TC_DC_WH }}
        shell: bash
        run: |
          # Get the next Friday's date (including today if it's Thursday)
          NEXT_TIME=$(date -u -d "next Fri" +%Y-%m-%d)

          # Set TC time at 09:00 UTC+0 on that Friday
          MEETING_TIME_UTC="${NEXT_TIME} 09:00:00"

          # Convert to Unix timestamp
          TIMESTAMP=$(date -d "$MEETING_TIME_UTC" +%s)

          # Create message
          MESSAGE="**Klefaski TC** Tomorrow <t:${TIMESTAMP}> <t:${TIMESTAMP}:R>."

          # Use jq to build JSON payload safely
          PAYLOAD=$(jq -n --arg msg "$MESSAGE" '{content: $msg}')

          # Send to Discord
          curl -H "Content-Type: application/json" -X POST -d "$PAYLOAD" "$DISCORD_WEBHOOK"
