name: Asiti 3-4 Hours Before
on:
  schedule:
    - cron: '0 2 * * 3'  # Every Wednsday at 06:00 UTC
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.TEST_ATZSRVR_WH }}
        shell: bash
        run: |
          # Get the next Friday's date (including today if it's Wednsday)
          NEXT_TIME=$(date -u -d "next Wed" +%Y-%m-%d)

          # Set meeting time at 02:00 UTC on that Wednsday
          MEETING_TIME_UTC="${NEXT_TIME} 14:00:00"

          # Convert to Unix timestamp
          TIMESTAMP=$(date -d "$MEETING_TIME_UTC" +%s)

          # Create message
          MESSAGE="**Asiti TC** soon <t:${TIMESTAMP}> <t:${TIMESTAMP}:R> prepare to send ship"

          # Use jq to build JSON payload safely
          PAYLOAD=$(jq -n --arg msg "$MESSAGE" '{content: $msg}')

          # Send to Discord
          curl -H "Content-Type: application/json" -X POST -d "$PAYLOAD" "$DISCORD_WEBHOOK"
