name: Weekly Discord Message

on:
  schedule:
    - cron: '0 12 * * 1'  # Every Monday at 12:00 UTC
  workflow_dispatch:  # Allows manual triggering too

jobs:
  post-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord message
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"@everyone Weekly meeting reminder! 🎉"}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
