name: send message with timestamp
on:
  schedule:
    - cron: '0 13 * * 5'  # Every Friday at 13:00 UTC
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.TEST_ATZSRVR_WH }}
        shell: bash
        run: |
          # Get the next Friday's date (including today if it's Friday)
          NEXT_FRIDAY=$(date -u -d "next Fri" +%Y-%m-%d)

          # Set meeting time at 14:00 UTC on that Friday
          MEETING_TIME_UTC="${NEXT_FRIDAY} 14:00:00"

          # Convert to Unix timestamp
          TIMESTAMP=$(date -d "$MEETING_TIME_UTC" +%s)

          # Create message
          MESSAGE="Meeting in 1h! <t:${TIMESTAMP}> <t:${TIMESTAMP}:R>"

          # Use jq to build JSON payload safely
          PAYLOAD=$(jq -n --arg msg "$MESSAGE" '{content: $msg}')

          # Send to Discord
          curl -H "Content-Type: application/json" -X POST -d "$PAYLOAD" "$DISCORD_WEBHOOK"
